import './globals.css'
import { Rubik } from 'next/font/google' //google fonts
import Navbar from './components/Navbar' 

const rubik = Rubik({ subsets: ['latin'] })


//meta data
export const metadata =  {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//children - page component currently being viewed
export default function RootLayout({children}){
  return(
    <html lang="en">    
      <body className={rubik.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
